[package]
name = "momotetsu"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["HtmlInputElement", "Document", "Element", "Window"] }

[lib]
crate-type = ["cdylib"]
